### ISSUE TITLE
Cleanup Mouse Capturing 

### ISSUE THREAD

**Issue by masonwr** [frustak/Quest#1]
I think you also need to `DisableMouseCapture` when you `cleanup_terminal`

something like 
```rust
fn cleanup_terminal(mut terminal: CrossTerminal) -> DynResult {
    disable_raw_mode()?;
    execute!(
        terminal.backend_mut(),
        LeaveAlternateScreen,
        DisableMouseCapture
    )?;

    Ok(())
}
```

Without this, after exiting Quest, when I used the scroll wheel on my mouse I noticed the terminal was filling up with garbo. (on Ubuntu 20.04)

**Comment by frustak** [comment]
Thanks, it seemed mouse capturing was never used so the program no longer enables it now.
