### ISSUE TITLE
More config options

### ISSUE THREAD

**Issue by mattheusroxas** [frustak/Quest#6]
### Create a configuration file so you configure the following (Use `$XDG_CONFIG_DIR` or I will eat you).

**1.** **Colors**; foreground and background, maybe even individual colors for things like selections.

**2.** **Keybindings**; Vi. Have some snippets in the readme so they can be used in the config file, I will gladly contribute them.

**Comment by frustak** [comment]
Both of them are supported now https://github.com/frustak/Quest/pull/14. It would be nice if you would contribute keybinding for Vi since I'm not familiar with it 😉 .

**Comment by mattheusroxas** [comment]
Thanks for the new additions, I'll try and add the bindings in my free time.
